const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');
const slugify = require('slugify');
const prisma = new PrismaClient();
const destinations = [
  {
    name: "Keraton Yogyakarta",
    type: "CULTURE",
    category: "Budaya",
    lat: -7.8053,
    lng: 110.3642,
    address: "Jl. Rotowijayan Blok No.1, Panembahan, Kraton, Yogyakarta",
    rating: 4.8,
    culturalValue: 5,
    ticketPrice: "Mulai sekitar Rp15.000-Rp25.000, cek loket resmi untuk update",
    openingHours: "Umumnya 08.00-14.00, Senin sering terbatas",
    bestTime: "Pagi hari saat area belum terlalu ramai",
    duration: "1,5-2,5 jam",
    tags: ["keraton", "budaya", "sejarah", "heritage", "keluarga"],
    description: "Jantung budaya Yogyakarta yang menyimpan kisah Kesultanan, tata ruang Jawa, dan peninggalan bersejarah yang masih hidup hingga hari ini.",
    story: "Keraton bukan sekadar bangunan istana, tetapi pusat kebudayaan yang memperlihatkan bagaimana tradisi Jawa dijaga lewat arsitektur, upacara, busana, gamelan, dan tata krama.",
    insight: "Datang pagi agar lebih nyaman menikmati museum, halaman keraton, dan suasana klasik kawasan Kraton.",
    imageUrl: "",
  },
  {
    name: "Taman Sari",
    type: "CULTURE",
    category: "Sejarah",
    lat: -7.8101,
    lng: 110.3594,
    address: "Patehan, Kraton, Yogyakarta",
    rating: 4.7,
    culturalValue: 5,
    ticketPrice: "Mulai sekitar Rp15.000-Rp25.000",
    openingHours: "Umumnya 09.00-15.00",
    bestTime: "Pagi atau menjelang sore untuk cahaya foto yang lembut",
    duration: "1-2 jam",
    tags: ["taman-sari", "sejarah", "arsitektur", "foto", "keraton"],
    description: "Bekas taman kerajaan dengan kolam pemandian, lorong bawah tanah, dan sudut arsitektur yang fotogenik.",
    story: "Taman Sari dahulu menjadi area peristirahatan keluarga kerajaan. Lorong, sumur gumuling, dan kolamnya membuat tempat ini terasa seperti labirin sejarah di tengah kota.",
    insight: "Gunakan alas kaki nyaman karena area kunjungannya berupa lorong, tangga, dan gang kampung.",
    imageUrl: "",
  },
  {
    name: "Malioboro",
    type: "TOURISM",
    category: "Ikonik",
    lat: -7.793,
    lng: 110.3658,
    address: "Jl. Malioboro, Sosromenduran, Gedong Tengen, Yogyakarta",
    rating: 4.8,
    culturalValue: 5,
    ticketPrice: "Gratis, siapkan biaya parkir/belanja",
    openingHours: "Area terbuka 24 jam, toko umumnya siang-malam",
    bestTime: "Sore hingga malam",
    duration: "1-3 jam",
    tags: ["malioboro", "belanja", "ikonik", "jalan-kaki", "oleh-oleh"],
    description: "Koridor paling legendaris di Jogja untuk berjalan santai, berburu oleh-oleh, menikmati suasana kota, dan merasakan denyut wisata Yogyakarta.",
    story: "Malioboro tumbuh sebagai ruang pertemuan wisatawan, pedagang, seniman jalanan, dan sejarah kota. Di sini Jogja terasa hidup dari pagi sampai malam.",
    insight: "Lebih nyaman berjalan kaki; gunakan kantong kecil dan jaga barang bawaan saat area ramai.",
    imageUrl: "",
  },
  {
    name: "Tugu Yogyakarta",
    type: "TOURISM",
    category: "Ikonik",
    lat: -7.7829,
    lng: 110.3671,
    address: "Cokrodiningratan, Jetis, Yogyakarta",
    rating: 4.7,
    culturalValue: 5,
    ticketPrice: "Gratis",
    openingHours: "Area publik 24 jam",
    bestTime: "Malam hari atau pagi sangat awal",
    duration: "20-45 menit",
    tags: ["tugu", "ikonik", "foto", "filosofi", "kota"],
    description: "Landmark ikonik Jogja yang menjadi simbol arah, filosofi, dan kenangan bagi banyak orang yang pernah singgah di Yogyakarta.",
    story: "Tugu berada pada garis imajiner antara Merapi, Keraton, dan Laut Selatan. Karena itu, ia bukan sekadar monumen, tetapi bagian dari filosofi tata ruang Jogja.",
    insight: "Berfoto dari trotoar dengan aman; jangan berdiri di tengah jalan karena lalu lintas cukup ramai.",
    imageUrl: "",
  },
  {
    name: "Museum Benteng Vredeburg",
    type: "CULTURE",
    category: "Sejarah",
    lat: -7.8002,
    lng: 110.3668,
    address: "Jl. Margo Mulyo No.6, Ngupasan, Yogyakarta",
    rating: 4.6,
    culturalValue: 5,
    ticketPrice: "Mulai sekitar Rp3.000-Rp10.000",
    openingHours: "Umumnya 08.00-15.30, Senin tutup",
    bestTime: "Pagi atau siang",
    duration: "1-2 jam",
    tags: ["museum", "sejarah", "vredeburg", "edukasi", "keluarga"],
    description: "Benteng kolonial yang kini menjadi museum perjuangan, cocok untuk memahami perjalanan sejarah Indonesia lewat diorama dan suasana bangunan tua.",
    story: "Bangunan ini pernah menjadi saksi masa kolonial dan dinamika politik Yogyakarta. Kini Vredeburg menawarkan cerita sejarah dengan cara yang mudah dinikmati keluarga.",
    insight: "Lokasinya dekat Malioboro dan Titik Nol, cocok digabung dalam satu rute jalan kaki.",
    imageUrl: "",
  },
  {
    name: "Museum Sonobudoyo",
    type: "CULTURE",
    category: "Budaya",
    lat: -7.8038,
    lng: 110.3633,
    address: "Jl. Pangurakan No.6, Ngupasan, Yogyakarta",
    rating: 4.7,
    culturalValue: 5,
    ticketPrice: "Mulai sekitar Rp10.000-Rp20.000",
    openingHours: "Umumnya 08.00-20.00, cek jadwal pertunjukan",
    bestTime: "Sore jika ingin lanjut pertunjukan wayang",
    duration: "1-2 jam",
    tags: ["museum", "wayang", "keris", "batik", "budaya"],
    description: "Museum budaya Jawa dengan koleksi wayang, keris, batik, topeng, dan benda tradisi yang membuat kisah Jawa terasa dekat.",
    story: "Sonobudoyo adalah tempat yang pas untuk memahami detail budaya Jawa tanpa harus membaca buku tebal. Koleksinya kaya, ruangnya nyaman, dan lokasinya sangat strategis.",
    insight: "Cek jadwal pertunjukan wayang malam agar kunjungan lebih berkesan.",
    imageUrl: "",
  },
  {
    name: "Kotagede",
    type: "CULTURE",
    category: "Sejarah",
    lat: -7.8281,
    lng: 110.3984,
    address: "Kotagede, Yogyakarta",
    rating: 4.7,
    culturalValue: 5,
    ticketPrice: "Gratis untuk kawasan, beberapa objek bisa berbayar sukarela",
    openingHours: "Kawasan terbuka, toko perak umumnya siang-sore",
    bestTime: "Pagi atau sore",
    duration: "2-3 jam",
    tags: ["kotagede", "perak", "mataram", "heritage", "kampung"],
    description: "Kawasan heritage bekas pusat Mataram Islam dengan gang tua, rumah tradisional, makam raja, dan sentra kerajinan perak.",
    story: "Kotagede menyimpan lapisan sejarah panjang Jogja. Dari tembok tua, pasar tradisional, sampai pengrajin perak, tiap sudutnya punya cerita.",
    insight: "Jelajahi pelan-pelan dengan berjalan kaki; beberapa area punya aturan berpakaian sopan.",
    imageUrl: "",
  },
  {
    name: "Kampung Wisata Tamansari",
    type: "CULTURE",
    category: "Budaya",
    lat: -7.8108,
    lng: 110.3577,
    address: "Patehan, Kraton, Yogyakarta",
    rating: 4.5,
    culturalValue: 4,
    ticketPrice: "Gratis untuk kampung, bayar sesuai aktivitas/workshop",
    openingHours: "Umumnya pagi-sore",
    bestTime: "Pagi atau sore",
    duration: "1-2 jam",
    tags: ["kampung-wisata", "batik", "mural", "lokal", "kerajinan"],
    description: "Kampung wisata di sekitar Taman Sari yang menawarkan suasana lokal, mural, batik, dan cerita kehidupan warga Kraton.",
    story: "Di balik area populer Taman Sari, kampung ini memperlihatkan Jogja yang lebih intim: lorong kecil, senyum warga, kerajinan, dan ritme kampung kota.",
    insight: "Hormati area rumah warga dan minta izin sebelum memotret aktivitas pribadi.",
    imageUrl: "",
  },
  {
    name: "Museum Ullen Sentalu",
    type: "CULTURE",
    category: "Budaya",
    lat: -7.5967,
    lng: 110.4233,
    address: "Jl. Boyong, Kaliurang, Hargobinangun, Sleman",
    rating: 4.8,
    culturalValue: 5,
    ticketPrice: "Mulai sekitar Rp50.000-Rp100.000 tergantung paket",
    openingHours: "Umumnya 08.30-16.00, Senin tutup",
    bestTime: "Pagi atau siang sejuk Kaliurang",
    duration: "1,5-2 jam",
    tags: ["museum", "jawa", "kaliurang", "budaya", "keluarga"],
    description: "Museum seni dan budaya Jawa di kawasan Kaliurang dengan narasi yang elegan tentang keluarga kerajaan, batik, dan kehidupan bangsawan.",
    story: "Ullen Sentalu terkenal karena cara bercerita yang immersive. Pengunjung diajak memahami sisi manusiawi sejarah Jawa melalui ruang-ruang museum yang tenang.",
    insight: "Ikuti tur resmi museum; sebagian area biasanya tidak boleh difoto.",
    imageUrl: "",
  },
  {
    name: "Candi Prambanan",
    type: "CULTURE",
    category: "Sejarah",
    lat: -7.752,
    lng: 110.4915,
    address: "Bokoharjo, Prambanan, Sleman",
    rating: 4.9,
    culturalValue: 5,
    ticketPrice: "Mulai sekitar Rp50.000 untuk wisatawan domestik, cek tarif resmi",
    openingHours: "Umumnya 06.30-17.00",
    bestTime: "Pagi atau sore menjelang sunset",
    duration: "2-3 jam",
    tags: ["candi", "prambanan", "unesco", "sejarah", "keluarga"],
    description: "Kompleks candi Hindu megah yang menjadi salah satu ikon terbesar Yogyakarta dan warisan budaya kelas dunia.",
    story: "Prambanan memukau lewat relief Ramayana, arsitektur menjulang, dan komposisi candi yang dramatis. Tempat ini cocok untuk wisata sejarah sekaligus foto lanskap.",
    insight: "Datang sore jika ingin lanjut menikmati Sendratari Ramayana pada jadwal tertentu.",
    imageUrl: "",
  },
  {
    name: "Ratu Boko",
    type: "CULTURE",
    category: "Sejarah",
    lat: -7.7705,
    lng: 110.4894,
    address: "Bokoharjo, Prambanan, Sleman",
    rating: 4.7,
    culturalValue: 5,
    ticketPrice: "Mulai sekitar Rp40.000-Rp50.000, cek tarif resmi",
    openingHours: "Umumnya 06.00-17.00",
    bestTime: "Sore hari untuk sunset",
    duration: "1,5-2,5 jam",
    tags: ["ratu-boko", "candi", "sunset", "sejarah", "foto"],
    description: "Kompleks situs arkeologi di atas bukit yang terkenal dengan gerbang batu dan panorama matahari terbenam.",
    story: "Ratu Boko memberi pengalaman berbeda dari candi biasa. Area luas, sisa bangunan, dan langit senja membuat tempat ini terasa sinematik.",
    insight: "Bawa air minum dan topi karena area terbuka cukup luas.",
    imageUrl: "",
  },
  {
    name: "Tebing Breksi",
    type: "TOURISM",
    category: "Alam",
    lat: -7.7816,
    lng: 110.5046,
    address: "Sambirejo, Prambanan, Sleman",
    rating: 4.6,
    culturalValue: 3,
    ticketPrice: "Retribusi/parkir terjangkau, cek loket setempat",
    openingHours: "Umumnya 06.00-21.00",
    bestTime: "Sore menjelang sunset",
    duration: "1-2 jam",
    tags: ["tebing-breksi", "alam", "foto", "sunset", "keluarga"],
    description: "Bekas tambang batu yang berubah menjadi destinasi kreatif dengan ukiran tebing, gardu pandang, dan panorama Jogja dari ketinggian.",
    story: "Tebing Breksi menunjukkan bagaimana ruang bekas tambang bisa bertransformasi menjadi destinasi wisata populer yang ramah keluarga.",
    insight: "Area batu bisa panas saat siang; sore hari biasanya lebih nyaman.",
    imageUrl: "",
  },
  {
    name: "HeHa Sky View",
    type: "TOURISM",
    category: "Foto",
    lat: -7.8495,
    lng: 110.4783,
    address: "Patuk, Gunungkidul, Yogyakarta",
    rating: 4.5,
    culturalValue: 2,
    ticketPrice: "Mulai sekitar Rp20.000-Rp30.000, spot foto tertentu bisa berbayar",
    openingHours: "Umumnya 10.00-21.00",
    bestTime: "Sore hingga malam",
    duration: "1,5-3 jam",
    tags: ["heha", "foto", "malam", "view", "keluarga"],
    description: "Tempat menikmati panorama kota dari perbukitan Patuk dengan spot foto modern dan suasana malam yang hidup.",
    story: "HeHa cocok untuk wisata santai setelah menjelajah kota. Lampu kota, angin bukit, dan spot foto membuatnya populer untuk keluarga dan anak muda.",
    insight: "Datang sebelum sunset agar dapat dua suasana: senja dan malam.",
    imageUrl: "",
  },
  {
    name: "Bukit Bintang",
    type: "TOURISM",
    category: "Alam",
    lat: -7.847,
    lng: 110.4798,
    address: "Jl. Wonosari, Patuk, Gunungkidul",
    rating: 4.5,
    culturalValue: 2,
    ticketPrice: "Gratis, biaya parkir/makan sesuai tempat",
    openingHours: "Area publik, warung biasanya sore-malam",
    bestTime: "Malam hari",
    duration: "1-2 jam",
    tags: ["bukit-bintang", "malam", "view", "kuliner", "patuk"],
    description: "Spot malam klasik untuk melihat lampu kota Jogja dari ketinggian sambil menikmati jagung bakar atau minuman hangat.",
    story: "Bukit Bintang punya daya tarik sederhana: duduk santai, ngobrol, menikmati angin malam, dan melihat Jogja berkelip dari kejauhan.",
    insight: "Gunakan jaket karena angin malam di kawasan Patuk bisa cukup dingin.",
    imageUrl: "",
  },
  {
    name: "Hutan Pinus Mangunan",
    type: "TOURISM",
    category: "Alam",
    lat: -7.9266,
    lng: 110.4318,
    address: "Mangunan, Dlingo, Bantul",
    rating: 4.6,
    culturalValue: 3,
    ticketPrice: "Retribusi/parkir terjangkau",
    openingHours: "Umumnya 06.00-17.30",
    bestTime: "Pagi hari",
    duration: "1-2 jam",
    tags: ["hutan-pinus", "mangunan", "alam", "foto", "keluarga"],
    description: "Hutan pinus sejuk di Bantul yang cocok untuk jalan santai, foto, dan menikmati suasana alam yang teduh.",
    story: "Deretan pinus tinggi memberi suasana tenang dan fotogenik. Tempat ini sering jadi pilihan keluarga yang ingin kabur sejenak dari hiruk-pikuk kota.",
    insight: "Pagi hari biasanya lebih sejuk dan cahaya matahari menembus pepohonan dengan indah.",
    imageUrl: "",
  },
  {
    name: "Kebun Buah Mangunan",
    type: "TOURISM",
    category: "Alam",
    lat: -7.9401,
    lng: 110.4266,
    address: "Mangunan, Dlingo, Bantul",
    rating: 4.6,
    culturalValue: 3,
    ticketPrice: "Retribusi/parkir terjangkau",
    openingHours: "Umumnya 05.00-17.00",
    bestTime: "Subuh-pagi untuk kabut dan sunrise",
    duration: "1-2 jam",
    tags: ["mangunan", "sunrise", "alam", "view", "keluarga"],
    description: "Spot gardu pandang yang terkenal dengan panorama lembah dan kabut pagi seperti negeri di atas awan.",
    story: "Kebun Buah Mangunan paling memikat saat pagi. Kabut yang menutup lembah membuat pemandangannya terasa dramatis dan menenangkan.",
    insight: "Datang sangat pagi jika ingin mengejar kabut dan sunrise.",
    imageUrl: "",
  },
  {
    name: "Pantai Parangtritis",
    type: "TOURISM",
    category: "Alam",
    lat: -8.0255,
    lng: 110.329,
    address: "Parangtritis, Kretek, Bantul",
    rating: 4.7,
    culturalValue: 5,
    ticketPrice: "Retribusi kawasan pantai, cek loket setempat",
    openingHours: "Area pantai terbuka, aktivitas aman saat terang",
    bestTime: "Sore menjelang sunset",
    duration: "1,5-3 jam",
    tags: ["parangtritis", "pantai", "sunset", "legenda", "keluarga"],
    description: "Pantai legendaris Jogja dengan ombak besar, gumuk pasir, delman, ATV, dan cerita budaya yang melekat kuat.",
    story: "Parangtritis bukan hanya pantai, tetapi juga bagian dari lanskap budaya Jogja yang terhubung dengan kisah Laut Selatan.",
    insight: "Jangan berenang terlalu jauh karena ombak selatan kuat; ikuti arahan petugas pantai.",
    imageUrl: "",
  },
  {
    name: "Gumuk Pasir Parangkusumo",
    type: "TOURISM",
    category: "Alam",
    lat: -8.0159,
    lng: 110.3158,
    address: "Parangkusumo, Kretek, Bantul",
    rating: 4.5,
    culturalValue: 4,
    ticketPrice: "Gratis/retribusi parkir, sandboarding bisa berbayar",
    openingHours: "Umumnya pagi-sore",
    bestTime: "Sore hari",
    duration: "1-2 jam",
    tags: ["gumuk-pasir", "parangkusumo", "foto", "sandboarding", "alam"],
    description: "Hamparan pasir unik dekat pantai yang menawarkan suasana seperti gurun kecil dan spot foto berbeda di Jogja.",
    story: "Gumuk Pasir terbentuk dari proses alam panjang yang melibatkan material vulkanik, sungai, angin, dan laut. Lanskapnya jarang ditemukan di Indonesia.",
    insight: "Sore lebih nyaman karena pasir tidak terlalu panas.",
    imageUrl: "",
  },
  {
    name: "Pantai Indrayanti",
    type: "TOURISM",
    category: "Alam",
    lat: -8.15,
    lng: 110.6121,
    address: "Tepus, Gunungkidul, Yogyakarta",
    rating: 4.6,
    culturalValue: 3,
    ticketPrice: "Retribusi kawasan pantai Gunungkidul",
    openingHours: "Area pantai, aman dikunjungi saat terang",
    bestTime: "Pagi atau sore",
    duration: "2-3 jam",
    tags: ["pantai", "gunungkidul", "pasir-putih", "keluarga", "foto"],
    description: "Pantai pasir putih di Gunungkidul dengan tebing karang, restoran tepi pantai, dan suasana liburan yang santai.",
    story: "Indrayanti populer karena aksesnya relatif mudah dan fasilitasnya lengkap. Cocok untuk wisata keluarga yang ingin menikmati pantai cantik tanpa terlalu ekstrem.",
    insight: "Tetap hati-hati dengan ombak selatan dan jangan berenang melewati batas aman.",
    imageUrl: "",
  },
  {
    name: "Pantai Timang",
    type: "TOURISM",
    category: "Alam",
    lat: -8.1746,
    lng: 110.6617,
    address: "Purwodadi, Tepus, Gunungkidul",
    rating: 4.6,
    culturalValue: 3,
    ticketPrice: "Retribusi dan wahana gondola/jembatan berbayar",
    openingHours: "Umumnya pagi-sore",
    bestTime: "Pagi hingga siang",
    duration: "2-3 jam",
    tags: ["pantai-timang", "gondola", "adrenalin", "gunungkidul", "laut"],
    description: "Pantai karang dengan gondola tradisional dan jembatan gantung menuju pulau kecil, cocok untuk pencari pengalaman unik.",
    story: "Dulu gondola Timang dipakai nelayan untuk menyeberang mencari lobster. Kini pengalaman itu menjadi daya tarik wisata yang memacu adrenalin.",
    insight: "Cek cuaca dan kondisi ombak sebelum mencoba wahana.",
    imageUrl: "",
  },
  {
    name: "Goa Pindul",
    type: "TOURISM",
    category: "Alam",
    lat: -7.9306,
    lng: 110.6494,
    address: "Bejiharjo, Karangmojo, Gunungkidul",
    rating: 4.6,
    culturalValue: 3,
    ticketPrice: "Paket cave tubing bervariasi, cek operator resmi",
    openingHours: "Umumnya pagi-sore",
    bestTime: "Pagi atau siang saat cuaca cerah",
    duration: "2-3 jam",
    tags: ["goa-pindul", "cave-tubing", "alam", "keluarga", "air"],
    description: "Wisata cave tubing menyusuri sungai bawah tanah dengan ban pelampung, pemandu lokal, dan suasana goa yang seru.",
    story: "Goa Pindul memadukan petualangan ringan dan edukasi alam. Jalurnya cocok untuk pemula karena dibantu pemandu dan perlengkapan keselamatan.",
    insight: "Bawa pakaian ganti dan simpan barang elektronik di dry bag.",
    imageUrl: "",
  },
  {
    name: "Kaliurang",
    type: "TOURISM",
    category: "Alam",
    lat: -7.596,
    lng: 110.4241,
    address: "Kaliurang, Hargobinangun, Sleman",
    rating: 4.6,
    culturalValue: 4,
    ticketPrice: "Tergantung objek/area, beberapa spot gratis",
    openingHours: "Kawasan terbuka, objek wisata mengikuti jam masing-masing",
    bestTime: "Pagi atau siang sejuk",
    duration: "2-4 jam",
    tags: ["kaliurang", "merapi", "sejuk", "alam", "keluarga"],
    description: "Kawasan lereng Merapi yang sejuk dengan museum, taman, kuliner jadah tempe, dan suasana pegunungan.",
    story: "Kaliurang telah lama menjadi tempat beristirahat warga Jogja. Udaranya sejuk dan pemandangannya mengarah ke sisi gagah Gunung Merapi.",
    insight: "Cocok digabung dengan Museum Ullen Sentalu atau jeep lava tour.",
    imageUrl: "",
  },
  {
    name: "Lava Tour Merapi",
    type: "TOURISM",
    category: "Petualangan",
    lat: -7.5815,
    lng: 110.4473,
    address: "Kawasan Kaliadem, Cangkringan, Sleman",
    rating: 4.7,
    culturalValue: 4,
    ticketPrice: "Paket jeep bervariasi, cek operator lokal",
    openingHours: "Umumnya pagi-sore",
    bestTime: "Pagi hari saat langit cerah",
    duration: "1,5-3 jam",
    tags: ["merapi", "jeep", "lava-tour", "petualangan", "alam"],
    description: "Tur jeep menyusuri kawasan bekas erupsi Merapi, museum mini, bunker, dan lanskap vulkanik yang dramatis.",
    story: "Lava Tour mengajak pengunjung memahami kekuatan alam Merapi sekaligus ketangguhan warga lereng gunung setelah erupsi.",
    insight: "Pilih operator resmi dan gunakan masker/kacamata jika jalur berdebu.",
    imageUrl: "",
  },
  {
    name: "Alun-Alun Kidul",
    type: "TOURISM",
    category: "Keluarga",
    lat: -7.8117,
    lng: 110.3635,
    address: "Patehan, Kraton, Yogyakarta",
    rating: 4.6,
    culturalValue: 5,
    ticketPrice: "Gratis, wahana/sepeda hias berbayar",
    openingHours: "Area publik 24 jam, ramai sore-malam",
    bestTime: "Malam hari",
    duration: "1-2 jam",
    tags: ["alkid", "keluarga", "malam", "tradisi", "kuliner"],
    description: "Ruang publik selatan Keraton yang ramai malam hari dengan sepeda hias, kuliner, dan tradisi masangin.",
    story: "Alun-Alun Kidul menjadi tempat santai warga dan wisatawan. Permainan melewati dua beringin dengan mata tertutup menambah unsur cerita dan hiburan.",
    insight: "Jaga anak-anak saat area ramai dan negosiasikan harga wahana sebelum naik.",
    imageUrl: "",
  },
  {
    name: "Pasar Beringharjo",
    type: "TOURISM",
    category: "Belanja",
    lat: -7.7989,
    lng: 110.3671,
    address: "Jl. Margo Mulyo No.16, Yogyakarta",
    rating: 4.6,
    culturalValue: 5,
    ticketPrice: "Gratis masuk",
    openingHours: "Umumnya 08.00-16.00",
    bestTime: "Pagi hingga siang",
    duration: "1-2 jam",
    tags: ["beringharjo", "batik", "belanja", "oleh-oleh", "pasar"],
    description: "Pasar legendaris untuk berburu batik, kain, jamu, jajanan, dan oleh-oleh khas Jogja dengan suasana tradisional.",
    story: "Beringharjo telah menjadi bagian penting denyut ekonomi Malioboro. Di sini pengalaman belanja terasa lebih hidup karena interaksi langsung dengan pedagang.",
    insight: "Siapkan uang tunai dan jangan ragu bertanya harga dengan sopan.",
    imageUrl: "",
  },
  {
    name: "Gudeg Yu Djum Wijilan",
    type: "CULINARY",
    category: "Kuliner",
    lat: -7.8066,
    lng: 110.3686,
    address: "Jl. Wijilan No.31, Panembahan, Yogyakarta",
    rating: 4.6,
    culturalValue: 4,
    ticketPrice: "Mulai sekitar Rp20.000-Rp60.000 per porsi/paket",
    openingHours: "Umumnya pagi-malam",
    bestTime: "Pagi atau siang",
    duration: "45-75 menit",
    tags: ["gudeg", "kuliner", "wijilan", "ikonik", "keluarga"],
    description: "Salah satu ikon gudeg Jogja dengan cita rasa manis-gurih khas, cocok untuk mengenal kuliner klasik Yogyakarta.",
    story: "Gudeg adalah rasa yang sangat lekat dengan Jogja. Di kawasan Wijilan, tradisi memasak nangka muda, krecek, telur, dan ayam terasa sebagai pengalaman kuliner budaya.",
    insight: "Rasa gudeg cenderung manis; padukan dengan sambal krecek jika ingin lebih pedas.",
    imageUrl: "",
  },
  {
    name: "Sate Klathak Pak Pong",
    type: "CULINARY",
    category: "Kuliner",
    lat: -7.8738,
    lng: 110.3879,
    address: "Jl. Sultan Agung No.18, Jejeran, Bantul",
    rating: 4.7,
    culturalValue: 4,
    ticketPrice: "Mulai sekitar Rp30.000-Rp70.000",
    openingHours: "Umumnya siang-malam",
    bestTime: "Sore atau malam",
    duration: "1-1,5 jam",
    tags: ["sate-klathak", "kuliner", "bantul", "kambing", "ikonik"],
    description: "Sate kambing khas Bantul yang ditusuk jeruji besi, berbumbu sederhana, dan terkenal karena rasa dagingnya yang kuat.",
    story: "Keunikan sate klathak ada pada bumbu minimalis dan tusuk besi yang membantu menghantarkan panas. Rasanya jujur, gurih, dan sangat khas Bantul.",
    insight: "Biasanya ramai pada jam makan malam; datang lebih awal jika ingin antre lebih singkat.",
    imageUrl: "",
  },
  {
    name: "Kopi Klotok",
    type: "CULINARY",
    category: "Kuliner",
    lat: -7.6488,
    lng: 110.4216,
    address: "Jl. Kaliurang KM 16, Pakem, Sleman",
    rating: 4.7,
    culturalValue: 4,
    ticketPrice: "Menu rumahan relatif terjangkau",
    openingHours: "Umumnya pagi-sore",
    bestTime: "Pagi menjelang siang",
    duration: "1-1,5 jam",
    tags: ["kopi-klotok", "kuliner", "rumahan", "sleman", "keluarga"],
    description: "Warung bernuansa rumah desa dengan menu sederhana seperti sayur lodeh, telur dadar, pisang goreng, dan kopi panas yang membuat rindu suasana kampung.",
    story: "Daya tarik Kopi Klotok bukan hanya rasa, tetapi atmosfer: dapur ramai, rumah joglo, sawah, dan makanan rumahan yang terasa akrab.",
    insight: "Datang pagi pada hari biasa agar suasana lebih santai.",
    imageUrl: "",
  },
  {
    name: "Bakpia Pathok 25",
    type: "CULINARY",
    category: "Oleh-oleh",
    lat: -7.7938,
    lng: 110.3566,
    address: "Jl. AIP II KS Tubun, Pathuk, Yogyakarta",
    rating: 4.6,
    culturalValue: 4,
    ticketPrice: "Harga per kotak bervariasi sesuai varian",
    openingHours: "Umumnya pagi-malam",
    bestTime: "Siang atau sore",
    duration: "30-60 menit",
    tags: ["bakpia", "oleh-oleh", "pathok", "kuliner", "belanja"],
    description: "Pusat oleh-oleh bakpia klasik Jogja dengan berbagai varian rasa untuk dibawa pulang.",
    story: "Bakpia telah menjadi oleh-oleh yang hampir wajib dari Jogja. Kawasan Pathuk dikenal sebagai salah satu sentra bakpia paling populer.",
    insight: "Cek tanggal produksi agar bakpia tetap segar sampai dibawa pulang.",
    imageUrl: "",
  },
  {
    name: "Angkringan Lik Man",
    type: "CULINARY",
    category: "Kuliner",
    lat: -7.7897,
    lng: 110.365,
    address: "Dekat Stasiun Tugu, Yogyakarta",
    rating: 4.5,
    culturalValue: 4,
    ticketPrice: "Menu angkringan terjangkau",
    openingHours: "Umumnya sore-malam",
    bestTime: "Malam hari",
    duration: "45-90 menit",
    tags: ["angkringan", "kopi-joss", "malam", "kuliner", "tugu"],
    description: "Angkringan legendaris dekat Stasiun Tugu yang terkenal dengan kopi joss dan suasana ngobrol malam khas Jogja.",
    story: "Angkringan adalah budaya makan sederhana yang merakyat. Di Lik Man, wisatawan bisa merasakan ritme malam Jogja lewat nasi kucing, gorengan, dan kopi arang.",
    insight: "Pilih tempat duduk yang aman dari lalu lintas dan nikmati pelan-pelan.",
    imageUrl: "",
  },
  {
    name: "House of Raminten",
    type: "CULINARY",
    category: "Kuliner",
    lat: -7.7821,
    lng: 110.37,
    address: "Jl. Faridan M Noto No.7, Kotabaru, Yogyakarta",
    rating: 4.5,
    culturalValue: 4,
    ticketPrice: "Menu bervariasi, umumnya terjangkau-menengah",
    openingHours: "Umumnya buka lama hingga malam",
    bestTime: "Siang atau malam",
    duration: "1-1,5 jam",
    tags: ["raminten", "kuliner", "jawa", "unik", "keluarga"],
    description: "Restoran bernuansa Jawa teatrikal dengan menu beragam, interior unik, dan pengalaman makan yang berbeda.",
    story: "Raminten memadukan kuliner, humor, dan estetika Jawa kontemporer. Cocok untuk wisatawan yang ingin suasana makan yang tidak biasa.",
    insight: "Menu sangat banyak; tanyakan rekomendasi pelayan jika bingung memilih.",
    imageUrl: "",
  },
  {
    name: "Tempo Gelato Prawirotaman",
    type: "CULINARY",
    category: "Kuliner",
    lat: -7.8197,
    lng: 110.3716,
    address: "Jl. Prawirotaman No.43, Yogyakarta",
    rating: 4.6,
    culturalValue: 2,
    ticketPrice: "Mulai sekitar Rp25.000-Rp50.000",
    openingHours: "Umumnya siang-malam",
    bestTime: "Siang saat cuaca panas",
    duration: "30-60 menit",
    tags: ["gelato", "prawirotaman", "kuliner", "anak-muda", "keluarga"],
    description: "Kedai gelato populer dengan banyak rasa dan suasana santai, cocok untuk jeda manis saat menjelajah kota.",
    story: "Di kawasan Prawirotaman yang ramai wisatawan, Tempo Gelato menjadi tempat singgah favorit untuk mendinginkan hari Jogja yang hangat.",
    insight: "Saat akhir pekan antrean bisa panjang; pilih jam di luar puncak.",
    imageUrl: "",
  },
  {
    name: "Jalan Prawirotaman",
    type: "TOURISM",
    category: "Kawasan",
    lat: -7.8199,
    lng: 110.3713,
    address: "Prawirotaman, Brontokusuman, Yogyakarta",
    rating: 4.5,
    culturalValue: 3,
    ticketPrice: "Gratis untuk kawasan",
    openingHours: "Kawasan terbuka, kafe/restoran sesuai jam masing-masing",
    bestTime: "Sore hingga malam",
    duration: "1-2 jam",
    tags: ["prawirotaman", "kafe", "jalan-santai", "wisatawan", "kuliner"],
    description: "Kawasan wisata kota dengan kafe, penginapan, restoran, toko kecil, dan suasana internasional yang tetap dekat dengan kampung Jogja.",
    story: "Prawirotaman sering disebut kampung turis. Namun di balik kafe dan hotelnya, kawasan ini tetap menyimpan ritme lokal yang menarik untuk dijelajahi.",
    insight: "Cocok untuk jalan santai setelah makan malam.",
    imageUrl: "",
  },
  {
    name: "Jalan Sosrowijayan",
    type: "TOURISM",
    category: "Kawasan",
    lat: -7.7912,
    lng: 110.3646,
    address: "Sosromenduran, Gedong Tengen, Yogyakarta",
    rating: 4.4,
    culturalValue: 3,
    ticketPrice: "Gratis untuk kawasan",
    openingHours: "Kawasan terbuka",
    bestTime: "Sore-malam",
    duration: "45-90 menit",
    tags: ["sosrowijayan", "malioboro", "kampung", "kuliner", "penginapan"],
    description: "Gang wisata dekat Malioboro dengan penginapan, kuliner, mural, dan suasana backpacker yang hangat.",
    story: "Sosrowijayan menjadi pintu kecil untuk melihat sisi Malioboro yang lebih kampung dan akrab.",
    insight: "Jelajahi dengan berjalan kaki karena gangnya relatif sempit.",
    imageUrl: "",
  },
  {
    name: "Masjid Gedhe Kauman",
    type: "CULTURE",
    category: "Religi",
    lat: -7.8033,
    lng: 110.3627,
    address: "Kauman, Kraton, Yogyakarta",
    rating: 4.8,
    culturalValue: 5,
    ticketPrice: "Gratis",
    openingHours: "Mengikuti waktu ibadah dan aturan masjid",
    bestTime: "Di luar waktu ibadah ramai",
    duration: "30-60 menit",
    tags: ["masjid-gedhe", "kauman", "religi", "sejarah", "keraton"],
    description: "Masjid bersejarah Kesultanan yang menjadi bagian penting dari tata ruang Keraton dan kehidupan keagamaan Yogyakarta.",
    story: "Masjid Gedhe Kauman memperlihatkan hubungan erat antara budaya, spiritualitas, dan kekuasaan tradisional Jawa.",
    insight: "Gunakan pakaian sopan dan jaga ketenangan area ibadah.",
    imageUrl: "",
  },
  {
    name: "Kampung Kauman",
    type: "CULTURE",
    category: "Budaya",
    lat: -7.8028,
    lng: 110.3615,
    address: "Kauman, Gondomanan, Yogyakarta",
    rating: 4.5,
    culturalValue: 5,
    ticketPrice: "Gratis untuk kawasan",
    openingHours: "Kawasan permukiman, kunjungi dengan sopan",
    bestTime: "Pagi atau sore",
    duration: "45-90 menit",
    tags: ["kauman", "kampung", "muhammadiyah", "sejarah", "religi"],
    description: "Kampung bersejarah dekat Keraton yang lekat dengan perkembangan pendidikan, dakwah, dan gerakan sosial di Yogyakarta.",
    story: "Kauman memiliki lorong-lorong kecil dan rumah tua yang menyimpan banyak cerita tentang kehidupan religius dan sosial masyarakat Jogja.",
    insight: "Karena kawasan permukiman, hormati privasi warga dan jangan membuat bising.",
    imageUrl: "",
  },
  {
    name: "Museum Affandi",
    type: "CULTURE",
    category: "Seni",
    lat: -7.7828,
    lng: 110.3964,
    address: "Jl. Laksda Adisucipto No.167, Yogyakarta",
    rating: 4.6,
    culturalValue: 4,
    ticketPrice: "Mulai sekitar Rp25.000-Rp50.000",
    openingHours: "Umumnya 09.00-16.00, Senin tutup",
    bestTime: "Pagi atau siang",
    duration: "1-1,5 jam",
    tags: ["affandi", "museum", "seni", "lukisan", "edukasi"],
    description: "Museum seni yang menampilkan karya dan kehidupan Affandi, salah satu pelukis besar Indonesia.",
    story: "Bangunan museum yang unik dan koleksi lukisannya membuat pengunjung masuk ke dunia ekspresi Affandi yang kuat dan emosional.",
    insight: "Cocok untuk wisatawan yang suka seni visual dan suasana museum yang lebih personal.",
    imageUrl: "",
  },
  {
    name: "Desa Wisata Kasongan",
    type: "CULTURE",
    category: "Kerajinan",
    lat: -7.8468,
    lng: 110.3423,
    address: "Kasongan, Bangunjiwo, Bantul",
    rating: 4.6,
    culturalValue: 4,
    ticketPrice: "Gratis untuk kawasan, belanja/workshop sesuai aktivitas",
    openingHours: "Toko umumnya pagi-sore",
    bestTime: "Pagi atau siang",
    duration: "1-2 jam",
    tags: ["kasongan", "gerabah", "kerajinan", "bantul", "belanja"],
    description: "Sentra gerabah Bantul dengan deretan toko kerajinan tanah liat, dekorasi rumah, dan workshop kreatif.",
    story: "Kasongan menunjukkan wajah kreatif masyarakat Bantul. Dari tanah liat, lahir karya yang bisa menjadi oleh-oleh, dekorasi, atau pengalaman belajar.",
    insight: "Tanyakan opsi pengiriman jika membeli kerajinan besar.",
    imageUrl: "",
  },
  {
    name: "Desa Wisata Krebet",
    type: "CULTURE",
    category: "Kerajinan",
    lat: -7.886,
    lng: 110.2949,
    address: "Sendangsari, Pajangan, Bantul",
    rating: 4.5,
    culturalValue: 4,
    ticketPrice: "Gratis untuk kawasan, workshop/belanja sesuai aktivitas",
    openingHours: "Umumnya pagi-sore",
    bestTime: "Pagi atau siang",
    duration: "1,5-2,5 jam",
    tags: ["krebet", "batik-kayu", "kerajinan", "desa-wisata", "bantul"],
    description: "Desa wisata kreatif yang terkenal dengan batik kayu, suasana pedesaan, dan aktivitas edukasi kerajinan.",
    story: "Krebet membuktikan batik tidak hanya hadir di kain. Motif tradisional dipindahkan ke media kayu dan menjadi karya khas desa.",
    insight: "Hubungi pengelola desa wisata jika ingin paket workshop kelompok.",
    imageUrl: "",
  },
  {
    name: "Desa Wisata Tembi",
    type: "CULTURE",
    category: "Budaya",
    lat: -7.8726,
    lng: 110.3546,
    address: "Timbulharjo, Sewon, Bantul",
    rating: 4.5,
    culturalValue: 4,
    ticketPrice: "Tergantung aktivitas/paket",
    openingHours: "Umumnya pagi-sore",
    bestTime: "Pagi atau sore",
    duration: "1,5-3 jam",
    tags: ["tembi", "desa-wisata", "budaya", "tradisi", "bantul"],
    description: "Desa wisata budaya dengan suasana pedesaan, aktivitas tradisional, dan ruang belajar budaya Jawa.",
    story: "Tembi cocok untuk memahami Jogja di luar keramaian kota. Pengunjung bisa merasakan atmosfer desa, seni, dan keramahtamahan warga.",
    insight: "Cocok untuk rombongan karena banyak aktivitas bisa dikemas paket.",
    imageUrl: "",
  },
  {
    name: "Desa Wisata Pentingsari",
    type: "CULTURE",
    category: "Desa Wisata",
    lat: -7.6339,
    lng: 110.4307,
    address: "Umbulharjo, Cangkringan, Sleman",
    rating: 4.7,
    culturalValue: 4,
    ticketPrice: "Tergantung paket wisata desa",
    openingHours: "Dengan reservasi/pengelola",
    bestTime: "Pagi hingga siang",
    duration: "2-4 jam",
    tags: ["pentingsari", "desa-wisata", "merapi", "edukasi", "keluarga"],
    description: "Desa wisata lereng Merapi dengan aktivitas edukasi, alam, permainan tradisional, dan kehidupan desa.",
    story: "Pentingsari menawarkan pengalaman tinggal dan belajar bersama warga. Cocok untuk sekolah, keluarga, atau wisatawan yang ingin lebih dekat dengan kehidupan desa.",
    insight: "Reservasi lebih dulu jika ingin kegiatan lengkap.",
    imageUrl: "",
  },
  {
    name: "Sendratari Ramayana Prambanan",
    type: "CULTURE",
    category: "Seni",
    lat: -7.7526,
    lng: 110.4918,
    address: "Kompleks Candi Prambanan, Sleman",
    rating: 4.8,
    culturalValue: 5,
    ticketPrice: "Harga tiket tergantung kelas dan panggung",
    openingHours: "Mengikuti jadwal pertunjukan malam",
    bestTime: "Malam hari saat pertunjukan",
    duration: "2 jam",
    tags: ["ramayana", "prambanan", "tari", "pertunjukan", "budaya"],
    description: "Pertunjukan tari kolosal yang menghidupkan kisah Ramayana dengan latar megah Candi Prambanan.",
    story: "Perpaduan tari, musik, kostum, dan latar candi membuat Sendratari Ramayana menjadi salah satu pengalaman budaya paling berkesan di Jogja.",
    insight: "Cek jadwal panggung terbuka/tertutup dan pesan tiket lebih awal saat musim liburan.",
    imageUrl: "",
  },
  {
    name: "Titik Nol Kilometer Yogyakarta",
    type: "TOURISM",
    category: "Ikonik",
    lat: -7.8015,
    lng: 110.3647,
    address: "Ngupasan, Gondomanan, Yogyakarta",
    rating: 4.7,
    culturalValue: 4,
    ticketPrice: "Gratis",
    openingHours: "Area publik 24 jam",
    bestTime: "Sore hingga malam",
    duration: "30-90 menit",
    tags: ["titik-nol", "ikonik", "foto", "malioboro", "kota"],
    description: "Ruang kota populer di ujung Malioboro dengan bangunan heritage, lampu malam, dan suasana Jogja yang meriah.",
    story: "Titik Nol menjadi simpul pertemuan banyak rute wisata kota: Malioboro, Vredeburg, Beringharjo, Gedung Agung, dan Keraton.",
    insight: "Malam hari ramai; tetap perhatikan barang bawaan.",
    imageUrl: "",
  },
  {
    name: "Gedung Agung Yogyakarta",
    type: "CULTURE",
    category: "Sejarah",
    lat: -7.8008,
    lng: 110.3646,
    address: "Jl. Ahmad Yani, Ngupasan, Yogyakarta",
    rating: 4.5,
    culturalValue: 5,
    ticketPrice: "Tidak selalu terbuka umum, cek agenda resmi",
    openingHours: "Terbatas sesuai agenda",
    bestTime: "Dilihat dari kawasan Titik Nol",
    duration: "15-30 menit",
    tags: ["gedung-agung", "sejarah", "presiden", "titik-nol", "heritage"],
    description: "Istana Kepresidenan Yogyakarta yang menjadi saksi penting masa awal Republik Indonesia.",
    story: "Gedung Agung berkaitan erat dengan periode Yogyakarta sebagai pusat pemerintahan RI. Bangunannya memperkuat nuansa heritage kawasan Titik Nol.",
    insight: "Biasanya dinikmati dari luar saat berjalan di kawasan Titik Nol.",
    imageUrl: "",
  },
  {
    name: "Jalan Wijilan",
    type: "CULINARY",
    category: "Kuliner",
    lat: -7.8065,
    lng: 110.3682,
    address: "Wijilan, Panembahan, Yogyakarta",
    rating: 4.6,
    culturalValue: 4,
    ticketPrice: "Bervariasi sesuai warung gudeg",
    openingHours: "Umumnya pagi-malam",
    bestTime: "Pagi atau siang",
    duration: "45-90 menit",
    tags: ["wijilan", "gudeg", "kuliner", "keraton", "keluarga"],
    description: "Kawasan kuliner gudeg dekat Keraton yang cocok untuk mencicipi rasa klasik Jogja dalam banyak pilihan warung.",
    story: "Wijilan adalah salah satu titik terbaik untuk mengenal gudeg. Aroma nangka muda, krecek, dan ayam kampung membuat jalan ini terasa sangat Jogja.",
    insight: "Bandingkan menu beberapa warung jika ingin memilih rasa gudeg yang sesuai selera.",
    imageUrl: "",
  },
  {
    name: "Sindu Kusuma Edupark",
    type: "TOURISM",
    category: "Keluarga",
    lat: -7.7675,
    lng: 110.354,
    address: "Jl. Jambon, Sinduadi, Sleman",
    rating: 4.4,
    culturalValue: 2,
    ticketPrice: "Tiket/wahana bervariasi",
    openingHours: "Umumnya siang-malam, cek jadwal terbaru",
    bestTime: "Sore hingga malam",
    duration: "2-3 jam",
    tags: ["keluarga", "wahana", "bianglala", "anak", "sleman"],
    description: "Taman rekreasi keluarga dengan wahana permainan, bianglala, dan suasana santai untuk anak-anak.",
    story: "SKE cocok untuk keluarga yang ingin jeda dari wisata sejarah dan alam dengan aktivitas hiburan yang lebih ringan.",
    insight: "Cek jam operasional terbaru karena bisa berubah sesuai hari dan musim.",
    imageUrl: "",
  },
  {
    name: "Gembira Loka Zoo",
    type: "TOURISM",
    category: "Keluarga",
    lat: -7.8063,
    lng: 110.3962,
    address: "Jl. Kebun Raya No.2, Yogyakarta",
    rating: 4.7,
    culturalValue: 3,
    ticketPrice: "Mulai sekitar Rp60.000-Rp75.000, cek tarif resmi",
    openingHours: "Umumnya 08.00-16.00",
    bestTime: "Pagi hari",
    duration: "2-4 jam",
    tags: ["kebun-binatang", "keluarga", "anak", "edukasi", "gembira-loka"],
    description: "Kebun binatang dan taman edukasi satwa yang cocok untuk wisata keluarga dan anak-anak.",
    story: "Gembira Loka menawarkan pengalaman belajar satwa yang mudah dinikmati semua umur, dengan area luas dan fasilitas keluarga.",
    insight: "Datang pagi agar satwa lebih aktif dan cuaca belum terlalu panas.",
    imageUrl: "",
  },
  {
    name: "Jogja National Museum",
    type: "CULTURE",
    category: "Seni",
    lat: -7.8007,
    lng: 110.3526,
    address: "Jl. Prof. Ki Amri Yahya No.1, Wirobrajan, Yogyakarta",
    rating: 4.6,
    culturalValue: 4,
    ticketPrice: "Tergantung pameran/acara",
    openingHours: "Mengikuti jadwal pameran",
    bestTime: "Saat ada pameran seni",
    duration: "1-2 jam",
    tags: ["jnm", "seni", "pameran", "kontemporer", "budaya"],
    description: "Ruang seni kontemporer yang sering menjadi lokasi pameran, festival, dan kegiatan kreatif di Jogja.",
    story: "JNM memperlihatkan sisi Jogja sebagai kota seni yang terus bergerak, dari seniman muda sampai agenda berskala besar.",
    insight: "Cek agenda pameran sebelum datang agar kunjungan tidak kosong.",
    imageUrl: "",
  },
  {
    name: "Puncak Becici",
    type: "TOURISM",
    category: "Alam",
    lat: -7.9023,
    lng: 110.4417,
    address: "Muntuk, Dlingo, Bantul",
    rating: 4.6,
    culturalValue: 3,
    ticketPrice: "Retribusi/parkir terjangkau",
    openingHours: "Umumnya 06.00-18.00",
    bestTime: "Pagi atau sore",
    duration: "1-2 jam",
    tags: ["becici", "mangunan", "hutan", "view", "foto"],
    description: "Spot hutan pinus dan gardu pandang di Dlingo dengan panorama perbukitan yang teduh dan menenangkan.",
    story: "Puncak Becici menawarkan suasana alam yang sederhana tetapi memikat: pinus, angin bukit, dan pemandangan terbuka.",
    insight: "Sore hari cocok untuk foto, tapi pastikan turun sebelum terlalu gelap.",
    imageUrl: "",
  },
  {
    name: "Seribu Batu Songgo Langit",
    type: "TOURISM",
    category: "Alam",
    lat: -7.9312,
    lng: 110.4304,
    address: "Mangunan, Dlingo, Bantul",
    rating: 4.5,
    culturalValue: 3,
    ticketPrice: "Retribusi/parkir terjangkau",
    openingHours: "Umumnya 07.00-17.00",
    bestTime: "Pagi atau sore",
    duration: "1-2 jam",
    tags: ["songgo-langit", "rumah-hobbit", "mangunan", "keluarga", "foto"],
    description: "Destinasi hutan di Mangunan dengan spot foto, rumah hobbit, dan suasana keluarga yang ringan.",
    story: "Seribu Batu cocok untuk wisatawan yang ingin berjalan santai di alam tanpa jalur terlalu berat.",
    insight: "Gunakan sepatu nyaman karena beberapa jalur sedikit menanjak.",
    imageUrl: "",
  },
  {
    name: "Pule Payung",
    type: "TOURISM",
    category: "Alam",
    lat: -7.805,
    lng: 110.1207,
    address: "Hargotirto, Kokap, Kulon Progo",
    rating: 4.5,
    culturalValue: 3,
    ticketPrice: "Retribusi dan spot foto/wahana bervariasi",
    openingHours: "Umumnya pagi-sore",
    bestTime: "Pagi atau sore",
    duration: "1-2 jam",
    tags: ["pule-payung", "kulon-progo", "view", "waduk-sermo", "foto"],
    description: "Spot foto dan gardu pandang di perbukitan Kulon Progo dengan panorama Waduk Sermo.",
    story: "Pule Payung memperkenalkan sisi barat Jogja yang hijau dan tenang, cocok untuk wisata pemandangan.",
    insight: "Perjalanan cukup jauh dari kota; gabungkan dengan Waduk Sermo atau Kalibiru.",
    imageUrl: "",
  },
  {
    name: "Waduk Sermo",
    type: "TOURISM",
    category: "Alam",
    lat: -7.823,
    lng: 110.1229,
    address: "Hargowilis, Kokap, Kulon Progo",
    rating: 4.6,
    culturalValue: 3,
    ticketPrice: "Retribusi/parkir terjangkau",
    openingHours: "Area wisata umumnya pagi-sore",
    bestTime: "Sore atau pagi",
    duration: "1-2 jam",
    tags: ["waduk-sermo", "kulon-progo", "alam", "piknik", "keluarga"],
    description: "Danau buatan di Kulon Progo dengan suasana tenang, cocok untuk piknik ringan dan menikmati panorama air-perbukitan.",
    story: "Waduk Sermo menjadi ruang santai warga dan wisatawan yang ingin menikmati Jogja dari sisi yang lebih sepi dan hijau.",
    insight: "Jaga kebersihan area piknik dan jangan membuang sampah ke waduk.",
    imageUrl: "",
  },
  {
    name: "Kalibiru",
    type: "TOURISM",
    category: "Alam",
    lat: -7.8067,
    lng: 110.1288,
    address: "Hargowilis, Kokap, Kulon Progo",
    rating: 4.5,
    culturalValue: 3,
    ticketPrice: "Retribusi dan spot foto/wahana bervariasi",
    openingHours: "Umumnya pagi-sore",
    bestTime: "Pagi atau sore",
    duration: "1-2 jam",
    tags: ["kalibiru", "kulon-progo", "view", "foto", "alam"],
    description: "Destinasi perbukitan dengan gardu pandang menghadap Waduk Sermo dan lanskap hijau Kulon Progo.",
    story: "Kalibiru pernah menjadi ikon wisata foto alam Jogja. Pemandangan dari ketinggian tetap jadi daya tarik utamanya.",
    insight: "Datang saat cuaca cerah agar view Waduk Sermo terlihat jelas.",
    imageUrl: "",
  },
];
const quiz = [
  [
    "Mengapa Yogyakarta pernah menjadi ibu kota Republik Indonesia pada masa revolusi?",
    [
      "Karena Jakarta tidak aman setelah kedatangan kembali pasukan Belanda",
      "Karena Yogyakarta punya pelabuhan terbesar",
      "Karena pusat industri dipindahkan ke Jogja",
      "Karena semua kementerian sejak awal berdiri di Jogja"
    ],
    0,
    "sejarah",
    "Pada 1946, pusat pemerintahan RI dipindahkan ke Yogyakarta karena situasi Jakarta tidak aman pada masa revolusi kemerdekaan."
  ],
  [
    "Apa makna Tugu Jogja dalam imajinasi masyarakat Yogyakarta?",
    [
      "Simbol filosofi garis imajiner antara Merapi, Keraton, dan Laut Selatan",
      "Penanda batas kabupaten Sleman",
      "Monumen olahraga nasional",
      "Gerbang utama menuju bandara"
    ],
    0,
    "budaya",
    "Tugu Jogja sering dipahami sebagai bagian dari garis filosofi Yogyakarta yang menghubungkan Merapi, Keraton, dan Laut Selatan."
  ],
  [
    "Mengapa Keraton Yogyakarta penting dalam budaya Jawa?",
    [
      "Karena menjadi pusat tradisi, tata nilai, upacara, dan sejarah Kesultanan Yogyakarta",
      "Karena hanya berfungsi sebagai pusat belanja",
      "Karena merupakan candi Hindu tertua",
      "Karena dibangun sebagai terminal transportasi"
    ],
    0,
    "budaya",
    "Keraton bukan hanya bangunan wisata, tetapi pusat budaya hidup yang menjaga tradisi dan tata nilai Jawa."
  ],
  [
    "Apa daya tarik utama Taman Sari bagi wisatawan?",
    [
      "Jejak taman kerajaan, kolam pemandian, lorong, dan arsitektur bersejarah",
      "Arena balap motor",
      "Pusat perbelanjaan modern",
      "Kebun binatang terbesar"
    ],
    0,
    "sejarah",
    "Taman Sari menyimpan suasana klasik bekas taman kerajaan dengan kolam, lorong, dan struktur arsitektur yang fotogenik."
  ],
  [
    "Apa yang membuat Benteng Vredeburg menarik dikunjungi?",
    [
      "Bangunan kolonial yang kini menjadi museum sejarah perjuangan Indonesia",
      "Pantai pasir putih di tengah kota",
      "Pusat kuliner gudeg terbesar",
      "Candi Buddha kuno"
    ],
    0,
    "sejarah",
    "Vredeburg memadukan arsitektur kolonial dengan narasi sejarah perjuangan, lokasinya pun dekat Malioboro."
  ],
  [
    "Mengapa Malioboro sering dianggap wajah wisata Kota Jogja?",
    [
      "Karena menjadi koridor belanja, kuliner, jalan kaki, dan suasana kota yang ikonik",
      "Karena berada di puncak gunung",
      "Karena hanya buka setahun sekali",
      "Karena merupakan kawasan industri tertutup"
    ],
    0,
    "destinasi",
    "Malioboro terkenal sebagai ruang publik ikonik untuk belanja, kuliner, dan menikmati atmosfer kota."
  ],
  [
    "Apa yang identik dengan kawasan Kotagede?",
    [
      "Sejarah Mataram Islam dan kerajinan perak",
      "Perkebunan teh",
      "Pelabuhan ikan",
      "Tambang batubara"
    ],
    0,
    "budaya",
    "Kotagede dikenal sebagai kawasan bersejarah dan sentra kerajinan perak di Yogyakarta."
  ],
  [
    "Mengapa blangkon memiliki nilai budaya dalam busana Jawa?",
    [
      "Karena mencerminkan identitas, kerapian, dan filosofi tata busana pria Jawa",
      "Karena dipakai untuk berenang",
      "Karena hanya aksesori olahraga",
      "Karena berasal dari seragam militer modern"
    ],
    0,
    "budaya",
    "Blangkon bukan sekadar penutup kepala, melainkan bagian dari tata busana dan identitas budaya Jawa."
  ],
  [
    "Apa karakter rasa gudeg yang membuatnya sangat dikenal sebagai kuliner Jogja?",
    [
      "Manis dan gurih dari olahan nangka muda, santan, dan bumbu rempah",
      "Sangat asam dari fermentasi ikan",
      "Pedas dingin dari es batu",
      "Pahit karena daun teh"
    ],
    0,
    "kuliner",
    "Gudeg terkenal dengan rasa manis-gurih khas Jogja dan sering disajikan bersama krecek, ayam, telur, atau tahu tempe."
  ],
  [
    "Apa fungsi angkringan dalam budaya kota Jogja?",
    [
      "Ruang makan sederhana sekaligus tempat ngobrol lintas kalangan",
      "Tempat parkir khusus bus wisata",
      "Gedung pertunjukan formal",
      "Pusat administrasi pemerintah"
    ],
    0,
    "kuliner",
    "Angkringan menjadi ruang sosial yang santai, murah, dan akrab bagi mahasiswa, warga, dan wisatawan."
  ],
  [
    "Mengapa batik Yogyakarta sering memakai warna sogan/coklat klasik?",
    [
      "Karena berkaitan dengan pakem estetika dan tradisi batik keraton",
      "Karena semua pewarna modern dilarang",
      "Karena hanya tersedia warna coklat di toko",
      "Karena warna lain tidak bisa dipakai kain"
    ],
    0,
    "budaya",
    "Warna sogan dan motif klasik menjadi salah satu ciri batik tradisional yang lekat dengan lingkungan keraton."
  ],
  [
    "Apa yang membuat Sendratari Ramayana Prambanan menarik untuk wisata budaya?",
    [
      "Kisah epos Ramayana dipentaskan dengan tari, musik, kostum, dan latar candi",
      "Pertandingan sepak bola malam",
      "Festival makanan cepat saji",
      "Pameran kendaraan modern"
    ],
    0,
    "budaya",
    "Sendratari Ramayana menggabungkan seni tari, musik, cerita epos, dan lanskap Prambanan yang dramatis."
  ],
  [
    "Mengapa Alun-alun Kidul populer pada malam hari?",
    [
      "Suasana santai, sepeda hias, kuliner, dan tradisi masangin",
      "Arena ski salju",
      "Pasar elektronik terbesar",
      "Tempat pendaratan pesawat"
    ],
    0,
    "destinasi",
    "Alun-alun Kidul populer untuk bersantai, mencoba masangin, dan menikmati suasana malam Jogja."
  ],
  [
    "Apa filosofi umum dari garis imajiner Yogyakarta?",
    [
      "Keterhubungan alam, manusia, kekuasaan, dan spiritualitas dari Merapi-Keraton-Laut Selatan",
      "Jalur kereta api tercepat",
      "Batas administratif kecamatan",
      "Rute belanja modern"
    ],
    0,
    "budaya",
    "Garis imajiner menjadi konsep penting dalam tata ruang dan filosofi Yogyakarta."
  ],
  [
    "Apa yang sebaiknya dilakukan wisatawan saat berkunjung ke area keraton atau tempat sakral?",
    [
      "Menghormati aturan, berpakaian sopan, dan mengikuti arahan petugas",
      "Berteriak bebas di semua ruangan",
      "Menyentuh semua koleksi museum",
      "Membuang sampah sembarangan"
    ],
    0,
    "etika",
    "Wisata budaya membutuhkan sikap hormat agar pengalaman tetap nyaman bagi pengunjung dan penjaga tradisi."
  ],
  [
    "Mengapa Museum Sonobudoyo cocok untuk belajar budaya Jawa?",
    [
      "Koleksinya mencakup wayang, keris, batik, naskah, dan artefak budaya",
      "Karena berisi wahana air",
      "Karena khusus menjual gadget",
      "Karena hanya menampilkan olahraga modern"
    ],
    0,
    "budaya",
    "Sonobudoyo adalah salah satu museum penting untuk mengenal artefak dan seni budaya Jawa."
  ],
  [
    "Apa daya tarik Ullen Sentalu bagi pencinta sejarah budaya?",
    [
      "Narasi budaya Jawa dan keluarga kerajaan dengan suasana museum yang intim",
      "Pusat grosir oleh-oleh murah",
      "Arena balap sepeda",
      "Kawasan pantai pasir hitam"
    ],
    0,
    "budaya",
    "Ullen Sentalu dikenal dengan cara bercerita yang kuat tentang budaya Jawa dan keluarga kerajaan."
  ],
  [
    "Mengapa wisatawan sering mengunjungi Prawirotaman?",
    [
      "Nuansa kampung wisata dengan kafe, penginapan, dan kuliner yang ramah pelancong",
      "Karena menjadi pusat tambang emas",
      "Karena hanya berisi kantor pemerintahan",
      "Karena merupakan area industri tertutup"
    ],
    0,
    "kuliner",
    "Prawirotaman populer sebagai kawasan wisatawan dengan banyak kafe, penginapan, dan tempat makan."
  ],
  [
    "Apa yang membuat Parangtritis dikenal dalam wisata Jogja?",
    [
      "Pantai ikonik dengan ombak besar, gumuk pasir sekitar, dan cerita budaya Laut Selatan",
      "Danau buatan di tengah kota",
      "Candi di lereng Merapi",
      "Museum seni modern"
    ],
    0,
    "alam",
    "Parangtritis adalah pantai ikonik yang juga terkait kuat dengan imajinasi budaya Laut Selatan."
  ],
  [
    "Mengapa wisata kuliner bakpia erat dengan Jogja?",
    [
      "Bakpia menjadi oleh-oleh populer yang berkembang dari kawasan Pathuk dan sekitarnya",
      "Karena hanya dijual di bandara luar negeri",
      "Karena makanan pokok keraton",
      "Karena berasal dari daerah kutub"
    ],
    0,
    "kuliner",
    "Bakpia sudah menjadi oleh-oleh khas yang sangat melekat dengan perjalanan wisata di Yogyakarta."
  ]
];
async function main(){
  const adminPass = await bcrypt.hash('Admin12345',12);
  await prisma.user.upsert({where:{email:'admin@jogjasplorasi.local'},update:{role:'ADMIN'},create:{email:'admin@jogjasplorasi.local',passwordHash:adminPass,role:'ADMIN',profile:{create:{fullName:'JogjaSplorasi Admin'}},preferences:{create:{}}}});
  for (const destination of destinations) {
    const slug = slugify(destination.name, { lower: true, strict: true });
    const data = {
      name: destination.name,
      slug,
      type: destination.type,
      category: destination.category,
      latitude: destination.lat,
      longitude: destination.lng,
      description: destination.description,
      story: destination.story || null,
      localInsight: destination.insight || null,
      address: destination.address,
      imageUrl: destination.imageUrl || null,
      tags: destination.tags || [],
      culturalValue: destination.culturalValue || 3,
      rating: destination.rating || 4.5,
      isFeatured: (destination.culturalValue || 0) >= 4 || (destination.rating || 0) >= 4.7,
      openingHours: destination.openingHours || 'Cek informasi terbaru sebelum berangkat',
      ticketPrice: destination.ticketPrice || 'Cek informasi terbaru di loket/sumber resmi',
      bestTimeToVisit: destination.bestTime || 'Pagi atau sore',
      recommendedDuration: destination.duration || '1-2 jam',
      isActive: true,
      isVerified: true,
    };
    await prisma.destination.upsert({
      where: { slug },
      update: data,
      create: data,
    });
  }
  await prisma.quizAttemptAnswer.deleteMany();
  await prisma.quizOption.deleteMany();
  await prisma.quizQuestion.deleteMany();
  for (const q of quiz){
    const [questionText,options,correctIndex,category,explanation]=q;
    await prisma.quizQuestion.create({data:{questionText,category,explanation,options:{create:options.map((optionText,i)=>({optionText,isCorrect:i===correctIndex}))}}});
  }
  console.log(`Seed completed: ${destinations.length} destinations and ${quiz.length} quiz questions. Admin: admin@jogjasplorasi.local / Admin12345`);
}
main().catch((e)=>{ console.error(e); process.exit(1); }).finally(()=>prisma.$disconnect());
